version: '3.8'

services:
   estudio-bi-part-app:
      build:
         context: .
         dockerfile: Dockerfile
      working_dir: /app
      volumes:
         - ./:/app
         - /app/node_modules
      ports:
         - '3021:3021'
      env_file:
         - .env
      depends_on:
         - redis
      networks:
         - estudio-bi-part-network
      deploy:
         resources:
            limits:
               cpus: '0.5'
               memory: '400m'

   redis:
      image: redis:alpine
      ports:
         - '6379:6379'
      networks:
         - estudio-bi-part-network
      deploy:
         resources:
            limits:
               cpus: '0.25'
               memory: '150m'

networks:
   estudio-bi-part-network:
      driver: bridge
