version: '3.8'

services:
   estudio-bi-part-app:
      build:
         context: .
         dockerfile: Dockerfile.dev
      working_dir: /app
      volumes:
         - ./:/app
         - /app/node_modules
      ports:
         - '3022:3022'
      env_file:
         - .env
      depends_on:
         - redis
      networks:
         - estudio-bi-part-network

   redis:
      image: redis:alpine
      ports:
         - '6379:6379'
      networks:
         - estudio-bi-part-network

networks:
   estudio-bi-part-network:
      driver: bridge

volumes:
   postgres_data:
